// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asugaksharp.Infrastructure.Persistanse;

#nullable disable

namespace asugaksharp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250603052744_remove poles from kafedra")]
    partial class RemovePolesFromKafedra
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("asugaksharp.Model.Kafedra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kafedra");
                });

            modelBuilder.Entity("asugaksharp.Model.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dolgnost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPredsed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSecretar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVneshniy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsZavKaf")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KafedraID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stepen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Zvanie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KafedraID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("asugaksharp.Model.PeriodZasedania", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Primechanie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PeriodZasedania");
                });

            modelBuilder.Entity("asugaksharp.Model.Person", b =>
                {
                    b.HasOne("asugaksharp.Model.Kafedra", null)
                        .WithMany("Persons")
                        .HasForeignKey("KafedraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("asugaksharp.Model.Kafedra", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}