// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asugaksharp.Infrastructure.Persistence;

#nullable disable

namespace asugaksharp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204104228_UpdateOplataStructure")]
    partial class UpdateOplataStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GakPerson", b =>
                {
                    b.Property<Guid>("GaksId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonsId")
                        .HasColumnType("TEXT");

                    b.HasKey("GaksId", "PersonsId");

                    b.HasIndex("PersonsId");

                    b.ToTable("GakPerson");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Diplomnik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FioImen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FioRodit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("OrigVkr")
                        .HasColumnType("REAL");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Srball")
                        .HasColumnType("REAL");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZasedanieId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ZasedanieId");

                    b.ToTable("Diplomnik");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Docs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUploaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Docs");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Gak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPrikaza")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KafedraID")
                        .HasColumnType("TEXT");

                    b.Property<int>("KolvoBudget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KolvoPlatka")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomerPrikaza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Osnovanie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeriodZasedaniaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PredsedatelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SekretarId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KafedraID");

                    b.HasIndex("PeriodZasedaniaId");

                    b.HasIndex("PredsedatelId");

                    b.HasIndex("SekretarId");

                    b.ToTable("Gak");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Kafedra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kafedra");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.NapravleniePodgotovki", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazvanie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShifrNapr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NapravleniePodgotovki");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Normativ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("NormaVremeni")
                        .HasColumnType("REAL");

                    b.Property<string>("Osnovanie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RolVGek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("StavkaZaStudenta")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Normativ");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Oplata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("AkademChasov")
                        .HasColumnType("REAL");

                    b.Property<float>("AstronomChasov")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DataRascheta")
                        .HasColumnType("TEXT");

                    b.Property<int>("DogovorNumber")
                        .HasColumnType("INTEGER");

                    b.Property<float>("EnpProc")
                        .HasColumnType("REAL");

                    b.Property<float>("EnpSumma")
                        .HasColumnType("REAL");

                    b.Property<Guid>("GakId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDogovorGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Koefficient")
                        .HasColumnType("REAL");

                    b.Property<int>("KolvoBudget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KolvoPlatka")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoneySource")
                        .HasColumnType("INTEGER");

                    b.Property<float>("NdflProc")
                        .HasColumnType("REAL");

                    b.Property<float>("NdflSumma")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RolVGek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("StoimostChasa")
                        .HasColumnType("REAL");

                    b.Property<float>("SummaBezNalogov")
                        .HasColumnType("REAL");

                    b.Property<float>("SummaKVyplate")
                        .HasColumnType("REAL");

                    b.Property<float>("SummaSNalogami")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("ZasedanieId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GakId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ZasedanieId");

                    b.ToTable("Oplata");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.PeriodZasedania", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KafedraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Primechanie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KafedraId");

                    b.ToTable("PeriodZasedania");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dolgnost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPredsed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecenzent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSecretar")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVneshniy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsZavKaf")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KafedraID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportIssuedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNomer")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportSeria")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Snils")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stepen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Zvanie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KafedraID");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.PersonZasedanie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RolVGek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZasedanieId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("ZasedanieId");

                    b.ToTable("PersonZasedanie");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.ProfilPodgotovki", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NapravleniePodgotovkiID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShifrPodgot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NapravleniePodgotovkiID");

                    b.ToTable("ProfilPodgotovki");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Zasedanie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GakID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kvalificacia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NapravleniePodgotovki")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GakID");

                    b.ToTable("Zasedanie");
                });

            modelBuilder.Entity("GakPerson", b =>
                {
                    b.HasOne("asugaksharp.Core.Entities.Gak", null)
                        .WithMany()
                        .HasForeignKey("GaksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("asugaksharp.Core.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Diplomnik", b =>
                {
                    b.HasOne("asugaksharp.Core.Entities.Person", "Person")
                        .WithMany("Diplomniks")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("asugaksharp.Core.Entities.Zasedanie", "Zasedanie")
                        .WithMany("Diplomniks")
                        .HasForeignKey("ZasedanieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Zasedanie");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Docs", b =>
                {
                    b.HasOne("asugaksharp.Core.Entities.Person", "Person")
                        .WithMany("Docs")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Gak", b =>
                {
                    b.HasOne("asugaksharp.Core.Entities.Kafedra", "Kafedra")
                        .WithMany()
                        .HasForeignKey("KafedraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("asugaksharp.Core.Entities.PeriodZasedania", "PeriodZasedania")
                        .WithMany("Gaks")
                        .HasForeignKey("PeriodZasedaniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("asugaksharp.Core.Entities.Person", "Predsedatel")
                        .WithMany()
                        .HasForeignKey("PredsedatelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("asugaksharp.Core.Entities.Person", "Sekretar")
                        .WithMany()
                        .HasForeignKey("SekretarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kafedra");

                    b.Navigation("PeriodZasedania");

                    b.Navigation("Predsedatel");

                    b.Navigation("Sekretar");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Oplata", b =>
                {
                    b.HasOne("asugaksharp.Core.Entities.Gak", "Gak")
                        .WithMany()
                        .HasForeignKey("GakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("asugaksharp.Core.Entities.Person", "Person")
                        .WithMany("Oplatas")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("asugaksharp.Core.Entities.Zasedanie", null)
                        .WithMany("Oplatas")
                        .HasForeignKey("ZasedanieId");

                    b.Navigation("Gak");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.PeriodZasedania", b =>
                {
                    b.HasOne("asugaksharp.Core.Entities.Kafedra", "Kafedra")
                        .WithMany()
                        .HasForeignKey("KafedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kafedra");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Person", b =>
                {
                    b.HasOne("asugaksharp.Core.Entities.Kafedra", "Kafedra")
                        .WithMany()
                        .HasForeignKey("KafedraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kafedra");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.PersonZasedanie", b =>
                {
                    b.HasOne("asugaksharp.Core.Entities.Person", "Person")
                        .WithMany("PersonZasedanies")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("asugaksharp.Core.Entities.Zasedanie", "Zasedanie")
                        .WithMany("PersonZasedanies")
                        .HasForeignKey("ZasedanieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Zasedanie");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.ProfilPodgotovki", b =>
                {
                    b.HasOne("asugaksharp.Core.Entities.NapravleniePodgotovki", "NapravleniePodgotovki")
                        .WithMany("ProfilPodgotovkis")
                        .HasForeignKey("NapravleniePodgotovkiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NapravleniePodgotovki");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Zasedanie", b =>
                {
                    b.HasOne("asugaksharp.Core.Entities.Gak", "Gak")
                        .WithMany("Zasedanies")
                        .HasForeignKey("GakID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gak");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Gak", b =>
                {
                    b.Navigation("Zasedanies");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.NapravleniePodgotovki", b =>
                {
                    b.Navigation("ProfilPodgotovkis");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.PeriodZasedania", b =>
                {
                    b.Navigation("Gaks");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Person", b =>
                {
                    b.Navigation("Diplomniks");

                    b.Navigation("Docs");

                    b.Navigation("Oplatas");

                    b.Navigation("PersonZasedanies");
                });

            modelBuilder.Entity("asugaksharp.Core.Entities.Zasedanie", b =>
                {
                    b.Navigation("Diplomniks");

                    b.Navigation("Oplatas");

                    b.Navigation("PersonZasedanies");
                });
#pragma warning restore 612, 618
        }
    }
}
